[[manager.prepend_keymap]]
on = ["<C-i>"]
run = "plugin easyjump"
desc = "easyjump"

[[manager.prepend_keymap]]
on = ["<C-d>"]
run = "seek 10"
desc = "Scroll content down"

[[manager.prepend_keymap]]
on = ["<C-u>"]
run = "seek -10"
desc = "Scroll content up"

[[manager.prepend_keymap]]
on = ["Y", "Y"]
run = ["plugin system-clipboard"]
desc = "Copy to system-clipboard"

[[manager.prepend_keymap]]
on = ["g", "n"]
run = "cd ~/notes/obsidian/notes/"
desc = "Cd to notes directory"
