[[manager.prepend_keymap]]
on = ["<C-i>"]
run = "plugin easyjump"
desc = "easyjump"

[[manager.prepend_keymap]]
on = ["<C-d>"]
run = "seek 10"
desc = "Scroll content down"

[[manager.prepend_keymap]]
on = ["<C-u>"]
run = "seek -10"
desc = "Scroll content up"

[[manager.prepend_keymap]]
on = "<C-y>"
run = ["plugin system-clipboard"]
desc = "Copy to system-clipboard"
