return {
    "simrat39/symbols-outline.nvim",
    cmd = "SymbolsOutline",
    keys = { { "<leader>m", "<cmd>SymbolsOutline<cr>", desc = "Symbols Outline" } },
    config = {
        highlight_hovered_item = true,
        show_guides = true,
        auto_preview = false,
        position = "right",
        relative_width = true,
        width = 30,
        auto_close = false,
        show_numbers = false,
        show_relative_numbers = false,
        show_symbol_details = true,
        preview_bg_highlight = "Pmenu",
        autofold_depth = nil,
        auto_unfold_hover = true,
        fold_markers = { "", "" },
        wrap = false,
        keymaps = { -- These keymaps can be a string or a table for multiple keys
            close = { "<Esc>", "q" },
            goto_location = "o",
            focus_location = "<Cr>",
            hover_symbol = "i",
            toggle_preview = "p",
            rename_symbol = "r",
            code_actions = "a",
            fold = "<left>",
            unfold = "<right>",
            -- fold = "f",
            -- unfold = "u",
            fold_all = "f",
            unfold_all = "u",
            fold_reset = "R",
        },
        lsp_blacklist = {},
        symbol_blacklist = {},
        symbols = {
            File = { icon = "", hl = "@text.uri" },
            Module = { icon = " Mod", hl = "@namespace" },
            Namespace = { icon = "", hl = "@namespace" },
            Package = { icon = "", hl = "@namespace" },
            Class = { icon = "⦿ Class", hl = "@type" },
            Method = { icon = "  ƒ.", hl = "@method" },
            Property = { icon = "", hl = "@method" },
            Field = { icon = "", hl = "@field" },
            Constructor = { icon = "", hl = "@constructor" },
            Enum = { icon = "💥 Enum", hl = "@type" },
            Interface = { icon = "📦🚀Trait", hl = "@type" },
            Function = { icon = "", hl = "@function" },
            Variable = { icon = "🔸var ", hl = "@constant" },
            Constant = { icon = "📌Const", hl = "@constant" },
            String = { icon = "𝓐", hl = "@string" },
            Number = { icon = "#", hl = "@number" },
            Boolean = { icon = "⊨", hl = "@boolean" },
            Array = { icon = "", hl = "@constant" },
            Object = { icon = " 🧩", hl = "@type" },
            Key = { icon = "🔐", hl = "@type" },
            Null = { icon = "NULL", hl = "@type" },
            EnumMember = { icon = "", hl = "@field" },
            Struct = { icon = "⦿ Struct", hl = "@type" },
            Event = { icon = "🗲", hl = "@type" },
            Operator = { icon = "+", hl = "@operator" },
            TypeParameter = { icon = "𝙏 Type", hl = "@parameter" },
            Component = { icon = "", hl = "@function" },
            Fragment = { icon = "", hl = "@constant" },
        },
    },
}
