#!/usr/bin/env bash

flake=$(
	cat <<EOF
{
  description = "Development environment";
  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable-small";

  outputs =
    { self, flake-utils, nixpkgs }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.\${system};
      in
      {
        devShell = pkgs.mkShell {
          packages = with pkgs; [
		  # your dev packages here
          ];
          buildInputs = with pkgs; [ 
		  # your build inputs here
		  ];
        };
      }
    );
}
EOF
)

echo "$flake" >>flake.nix
echo "use flake" >>.envrc
direnv allow
