version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080 # qbittorrent
      - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
    volumes:
      # - /mnt/nas/backups/gluetun:/gluetun
      - /home/arar/docker/appdata/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      # - VPN_TYPE=wireguard
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=
      # # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=<YOUR_PRIVATE_KEY> # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      # - WIREGUARD_ADDRESSES=10.5.0.2/32
      # Timezone for accurate log times
      - TZ=Europe/London
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /home/arar/docker/appdata/qbittorrent:/config
      # - /mnt/nas/backups/mediaserver/qbittorrent:/config
      - /mnt/nas/data/torrents:/data/torrents
    depends_on:
      - gluetun
    restart: always

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/arar/docker/appdata/portainer:/data

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    network_mode: "service:gluetun"
    restart: always
    logging:
      driver: json-file
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/arar/docker/appdata/radarr:/config
      - /mnt/nas/data:/data

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    network_mode: "service:gluetun"
    restart: always
    logging:
      driver: json-file
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/arar/docker/appdata/sonarr:/config
      # - /data:/data
      - /mnt/nas/data:/data

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: always
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/arar/docker/appdata/bazarr:/config
      - /mnt/nas/data/media:/data/media

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    # ports:
    #   - 9696:9696
    network_mode: "service:gluetun"
    container_name: prowlarr
    # network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/arar/docker/appdata/prowlarr/data:/config
    restart: always

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    # network_mode: "host"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=192.168.2.10
    volumes:
      - /home/arar/docker/appdata/jellyfin:/config
      # - /mnt/nas/data/media:/data
      - /mnt/nas/data/media/movies:/data/movies
      - /mnt/nas/data/media/shows:/data/shows
    ports:
      - 8096:8096
    restart: always

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5055:5055
    volumes:
      - /home/arar/docker/appdata/jellyseerr:/app/config
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
    restart: always
