version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080 # qbittorrent
      - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
    volumes:
      - /home/arar/docker/appdata/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      # - VPN_TYPE=wireguard
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=
      - TZ=${TZ}
      - UPDATER_PERIOD=24h
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - /home/arar/docker/appdata/qbittorrent:/config
      - /home/arar/nas/server/data/torrents:/data/torrents
    depends_on:
      - gluetun
    restart: always

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/arar/docker/appdata/portainer:/data

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    network_mode: "service:gluetun"
    restart: always
    logging:
      driver: json-file
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/arar/docker/appdata/radarr:/config
      - /home/arar/nas/server/data:/data

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    network_mode: "service:gluetun"
    restart: always
    logging:
      driver: json-file
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/arar/docker/appdata/sonarr:/config
      - /home/arar/nas/server/data:/data

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: always
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/arar/docker/appdata/bazarr:/config
      - /home/arar/nas/server/data/media:/data/media

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    # ports:
    #   - 9696:9696
    network_mode: "service:gluetun"
    container_name: prowlarr
    # network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/arar/docker/appdata/prowlarr/data:/config
    restart: always

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${PUID}:${PGID}
    #group_add:
    #  - '109'  # This needs to be the group id of running `stat -c '%g' /dev/dri/renderD128` on the docker host
    environment:
      - TZ=Europe/London
    volumes:
      - /home/arar/docker/appdata/jellyfin/config:/config
      - /home/arar/docker/appdata/jellyfin/config:/jellyfin/cache:/cache
      - /home/arar/nas/server/data/media/movies:/Movies:ro
      - /home/arar/nas/server/data/media/shows:/Shows:ro
      - /home/arar/nas/server/data/books/:/Books:ro
      - /home/arar/nas/server/data/music:/Music:ro
    ports:
      - 8096:8096
    #  - 8920:8920 #optional
    #  - 7359:7359/udp #optional
    #  - 1900:1900/udp #optional
    #devices: uncomment these and amend if you require GPU accelerated transcoding
    #  - /dev/dri/renderD128:/dev/dri/renderD128
    #  - /dev/dri/card0:/dev/dri/card0
    restart: always

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      VERSION: docker
      # - PLEX_CLAIM= #optional
    volumes:
      - /home/arar/docker/appdata/plex:/config
      - /home/arar/nas/server/data/media/movies:/movies
      - /home/arar/nas/server/data/media/shows:/shows
    restart: always

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5055:5055
    volumes:
      - /home/arar/docker/appdata/jellyseerr:/app/config
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
    restart: always
