[bucket_list]
down = ["down"]
up = ["up"]
go_to_top = ["g"]
go_to_bottom = ["shift-g"]
page_down = ["ctrl-f"]
page_up = ["ctrl-b"]
select = ["enter"]

filter = ["/"]
sort = ["o"]
copy_details = ["r"]
refresh = ["shift-r"]
reset_filter = ["esc"]
management_console = ["x"]

[object_list]
down = ["down"]
up = ["up"]
go_to_top = ["g"]
go_to_bottom = ["shift-g"]
page_down = ["ctrl-f"]
page_up = ["ctrl-b"]
select = ["enter"]
back = ["backspace"]
bucket_list = ["~"]

download = ["s"]
download_as = ["shift-s"]
filter = ["/"]
sort = ["o"]
copy_details = ["r"]
refresh = ["shift-r"]
reset_filter = ["esc"]
management_console = ["x"]

[object_detail]
down = ["down"]
up = ["up"]
right = ["right"]
left = ["left"]
go_to_top = ["g"]
go_to_bottom = ["shift-g"]
back = ["backspace"]

download = ["s"]
download_as = ["shift-s"]
preview = ["p"]
copy_details = ["r"]
management_console = ["x"]

[object_preview]
down = ["down"]
up = ["up"]
right = ["right"]
left = ["left"]
go_to_top = ["g"]
go_to_bottom = ["shift-g"]
page_down = ["ctrl-f"]
page_up = ["ctrl-b"]
back = ["backspace"]

download = ["s"]
download_as = ["shift-s"]
encoding = ["e"]
toggle_wrap = ["w"]
toggle_number = ["n"]

[select_dialog]
down = ["down"]
up = ["up"]
right = ["right"]
left = ["left"]

close = ["esc"]
select = ["enter"]
