version: "3"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:stable
    container_name: nextcloud
    ports:
      - 9393:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/arar/docker/appdata/nextcloud:/config
      - /home/arar/nas/server/nextcloud/data:/data
    restart: always
