version: "3"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    ports:
      - 9393:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/arar/docker/appdata/nextcloud:/config
      - /home/arar/nas/server/nextcloud/data:/data
    restart: always

  # PAPERLESS-NGX
  broker:
    container_name: redis
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: always
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - /home/arar/nas/server/paperless/media/:/usr/src/paperless/media
      - /home/arar/docker/appdata/paperless:/usr/src/paperless/data
      - /home/arar/docker/appdata/paperless:/usr/src/paperless/export
      - /home/arar/docker/appdata/paperless:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIME_ZONE: ${TZ}
      PAPERLESS_OCR_LANGUAGES: eng nld

  gotenberg:
    container_name: gotenberg
    image: docker.io/gotenberg/gotenberg:7.10
    restart: always

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    container_name: tika
    image: ghcr.io/paperless-ngx/tika:latest
    restart: always

  # SYNCTHING ############################################
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/arar/docker/appdata/syncthing/config:/config
      - /home/arar/nas/:/nas
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: always

  # VAULTWARDEN ###########################################
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    ports:
      - 8081:80
    volumes:
      - "/home/arar/docker/appdata/vaultwarden/:/data/"
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - ADMIN_TOKEN=$VAULTWARDEN_ADMIN_TOKEN

  # CLOUDFLARE ############################################
  cloudflaretunnel:
    container_name: cloudflaredtunnel
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run

volumes:
  redisdata:
