base_url = "https://blog.arar.dev/"
title = "Arno's blog"
compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]
default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
author = "Arno"
