qprSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Commented
    filters: commenter:@me

issuesSections:
  - title: My Issues
    filters: author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me
  - title: Commented
    filters: is:open commenter:@me

defaults:
  prsLimit: 20
  issuesLimit: 20
  view: repo
  refetchIntervalMinutes: 10

  preview:
    open: true
    width: 100

  layout:
    prs:
      repoName:
        grow: true,
        width: 10
        hidden: false
      base:
        hidden: true
      # updatedAt:
      #   width: 7
      # repo:
      #   width: 15
      # author:
      #   width: 15
      # assignees:
      #   width: 20
      #   hidden: true
      # lines:
      #   width: 16

    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true

keybindings:
  universal:
    - key: E
      command: >
        cd {{.RepoPath}} && lazygit
  issues:
    - key: B
      command: >
        tmux display-popup -d {{.RepoPath}} -w 65 -h 10 -E 'ghprb {{.IssueNumber}}'
    - key: e
      command: >
        tmux new-window -c {{.RepoPath}} 'nvim -c ":silent Octo issue edit {{.IssueNumber}}"'
    - key: i
      command: >
        tmux display-popup -d {{.RepoPath}} -w 80% -h 90% -E 'nvim -c ":silent Octo issue create"'
  prs:
    - key: O
      command: >
        tmux new-window -c {{.RepoPath}} 'nvim -c ":silent Octo pr edit {{.PrNumber}}"'
# repoPaths:
#   Nutiliti/nutiliti: ~/c/nu/review
#   joshmedeski/*: ~/c/*
#   Learn-Build-Teach/deals-for-devs: ~/c/deals-for-devs
#   joshmedeski/t-smart-tmux-session-manager: ~/.config/tmux/plugins/t-smart-tmux-session-manager
#   joshmedeski/tmux-nerd-font-window-name: ~/.config/tmux/plugins/tmux-nerd-font-window-name
#   raycast/extensions: ~/c/raycast-extensions

theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false

pager:
  diff: "git-delta"
