version: "3"

services:
  bw-export:
    container_name: bw-export
    image: 0netx/bw-export
    volumes:
      - /home/arar/nas/server/backup/vaultwarden/arar/data/:/var/data
      - /home/arar/nas/server/backup/vaultwarden/arar/attachment/:/var/attachment
    environment:
      - BW_CLIENTID=$BW_CLIENTID
      - BW_CLIENTSECRET=$BW_CLIENTSECRET
      - BW_PASSWORD=$BW_PASSWORD
      - BW_URL_SERVER=$BW_URL_SERVER
      - EXPORT_PASSWORD=$EXPORT_PASSWORD
      - KEEP_LAST_BACKUPS=50
      # Optional: If not provided, the service will export all organizations in vault.
      # - BW_ORGANIZATIONS_LIST=<Organization list id, comma separated>
