gui:
  # stuff relating to the UI

  nerdFontsVersion: "3"
  scrollHeight: 2 # how many lines you scroll by
  scrollPastBottom: true # enable scrolling past the bottom
  sidePanelWidth: 0.25 # number from 0 to 1
  expandFocusedSidePanel: false
  mainPanelSplitMode: "flexible" # one of 'horizontal' | 'flexible' | 'vertical'
  language: "auto" # one of 'auto' | 'en' | 'zh' | 'pl' | 'nl'
  theme:
    selectedLineBgColor:
      # - reverse
      - black
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - black
    optionsTextColor:
      - black
    cherryPickedCommitBgColor:
      - blue
    cherryPickedCommitFgColor:
      - cyan
    unstagedChangesColor:
      - white
  commitLength:
    show: true
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: true
  showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: true
  showCommandLog: false
  showBottomLine: false
  commandLogSize: 8
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme gruvbox-dark
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium"
  parseEmoji: true
  log:
    # one of date-order, author-date-order, topo-order.
    # topo-order makes it easier to read the git log graph, but commits may not
    # appear chronologically. See https://git-scm.com/docs/git-log#_commit_ordering
    order: "topo-order"
    # one of always, never, when-maximised
    # this determines whether the git graph is rendered in the commits panel
    showGraph: "always"
    # displays the whole git graph by default in the commits panel (equivalent to passing the `--all` argument to `git log`)
    showWholeGraph: true
customCommands:
  - key: "f"
    command: "git difftool -y {{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}}"
    context: "commitFiles"
    description: "Compare (difftool) with local copy"
  - key: "s"
    command: "sesh connect '{{.SelectedWorktree.Path}}'"
    context: "worktrees"
    description: "Connect to session"
  - key: "E"
    context: "files"
    command: "gitmoji -c"
    loadingText: "Loading gitmoji"
    subprocess: true
keybinding:
  universal:
    togglePanel: "`"
    nextBlock-alt2: "~"
    prevBlock-alt2: "±"
    # prevBlock: "[" # go to next page in list
    # nextBlock: "]" # go to previous page in list
    prevTab: "<backtab>"
    nextTab: "<tab>"
