version: "3.7"
services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: tailscale
    environment:
      - TS_AUTHKEY= tskey-auth-kjgToUhCSf11CNTRL-xv86r9sHasgya2eEJeZksgtuqvPFKrop1
      - TS_STATE_DIR=/var/lib/tailscale
        - TS_EXTRA_ARGS=--advertise-exit-node --accept-dns=true
    volumes:
      - /home/arar/docker/appdata/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  nginx:
    image: nginx
    depends_on:
      - tailscale
    network_mode: service:tailscale
