#!/usr/bin/env bash

worktree_name="$1"

# Remove local worktree
git worktree remove -f "$worktree_name"

# Remove local branch and its tracking branch
git worktree prune

# Remove branch from origin
git push origin --delete "$worktree_name"

#Remove local branch if prune didnt work
git branch -d "$worktree_name"
