[settings]
mouse_mode = true

[keybindings.Menu]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Alt-1>" = "FocusMenu"
"<Alt-2>" = "FocusEditor"
"<Alt-3>" = "FocusData"
"<Alt-4>" = "FocusHistory"
"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"]" = "CycleFocusForwards"
"[" = "CycleFocusBackwards"

[keybindings.Editor]
"<Alt-q>" = "AbortQuery"
"Ctrl-s" = "SubmitEditorQuery"
"<Alt-1>" = "FocusMenu"
"<Alt-2>" = "FocusEditor"
"<Alt-3>" = "FocusData"
"<Alt-4>" = "FocusHistory"
"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"[" = "CycleFocusBackwards"
"]" = "CycleFocusForwards"

[keybindings.History]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Alt-1>" = "FocusMenu"
"<Alt-2>" = "FocusEditor"
"<Alt-3>" = "FocusData"
"<Alt-4>" = "FocusHistory"
"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"]" = "CycleFocusForwards"
"[" = "CycleFocusBackwards"

[keybindings.Data]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Alt-1>" = "FocusMenu"
"<Alt-2>" = "FocusEditor"
"<Alt-3>" = "FocusData"
"<Alt-4>" = "FocusHistory"
"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"]" = "CycleFocusForwards"
"[" = "CycleFocusBackwards"

[keybindings.PopUp]
"<Ctrl-c>" = "Quit"
